steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/imvest:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/imvest:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'imvest'
      - '--image'
      - 'gcr.io/$PROJECT_ID/imvest:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '100'
      - '--set-env-vars'
      - 'DATABASE_URL=$_DATABASE_URL,NEXTAUTH_SECRET=$_NEXTAUTH_SECRET,NEXTAUTH_URL=$_NEXTAUTH_URL'

images:
  - 'gcr.io/$PROJECT_ID/imvest:$COMMIT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
